ingress: https://flex.ansatt.dev.nav.no
azureTenant: trygdeetaten.no
allowAllUsers: true
env:
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: api://dev-gcp.flex.sykepengesoknad-backend/.default
  FLEX_INNTEKTSMELDING_STATUS_CLIENT_ID: api://dev-gcp.flex.flex-inntektsmelding-status/.default
  FLEX_ARBEIDSSOKERREGISTER_OPPDATERING_CLIENT_ID: api://dev-gcp.flex.flex-arbeidssokerregister-oppdatering/.default
  SPLEIS_SPORING_URL: https://sporing.ansatt.dev.nav.no
  SPANNER_URL: https://spanner.ansatt.dev.nav.no
