ingress: https://flex-internal.intern.dev.nav.no
azureTenant: trygdeetaten.no
allowAllUsers: true
env:
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: api://dev-gcp.flex.sykepengesoknad-backend/.default
  FLEX_INNTEKTSMELDING_STATUS_CLIENT_ID: api://dev-gcp.flex.flex-inntektsmelding-status/.default
