apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-internal-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 150Mi
  liveness:
    path: api/internal/isAlive
  readiness:
    path: api/internal/isReady
  startup:
    path: api/internal/isAlive
    initialDelay: 10
  azure:
    application:
      tenant: {{azureTenant}}
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: false
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-backend
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
