ingress: https://flex.ansatt.nav.no
azureTenant: nav.no
allowAllUsers: false
env:
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: api://prod-gcp.flex.sykepengesoknad-backend/.default
  FLEX_INNTEKTSMELDING_STATUS_CLIENT_ID: api://prod-gcp.flex.flex-inntektsmelding-status/.default
  FLEX_ARBEIDSSOKERREGISTER_OPPDATERING_CLIENT_ID: api://prod-gcp.flex.flex-arbeidssokerregister-oppdatering/.default
  SPLEIS_SPORING_URL: https://sporing.ansatt.nav.no
  SPANNER_URL: https://spanner.ansatt.nav.no
