name: workflow
on:
  workflow_dispatch:
  push:

jobs:
  felles-workflow:
    uses: navikt/flex-github-actions-workflows/.github/workflows/next-js-lightweight-pnpm.yml@main
    permissions:
      packages: read
      contents: read
      id-token: write
      security-events: write
      actions: read
    secrets: inherit

  tester:
    name: Kjør tester
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.0.0 --activate
      - run: pnpm install --frozen-lockfile
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm run test
